language: android
dist: trusty
android:
  components:
  
    - build-tools-26.0.2

    - android-26
    
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
